Workaround undefined reference to symbol 'EVP_DigestInit_ex@@OPENSSL_3.0.0'
Addressing
/usr/bin/ld: /tmp/ccLqDuAW.ltrans73.ltrans.o: undefined reference to symbol 'EVP_DigestInit_ex@@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib64/libcrypto.so.3: error adding symbols: DSO missing from command line